#!/bin/sh

# script/test: Builds the app


set -e

cd "$(dirname "$0")/.."

[ -z "$DEBUG" ] || set -x

PROJECT_ROOT="$(cd "$(dirname "$0")"/.. && pwd)"
export PATH="$PROJECT_ROOT/node_modules/.bin:$PATH"

cp src/index.html dist/index.html
cp -r src/data dist/data

babel src/recycling-map.js | uglifyjs -c -m > dist/recycling-map.min.js
babel src/segmented-circle-icon.js | uglifyjs -c -m > dist/segmented-circle-icon.min.js

#sass -t compressed style.scss:style.css
node-sass --output-style compressed src/style.scss dist/style.css
