#!/bin/sh

# script/test: Builds the app


set -e

cd "$(dirname "$0")/.."

[ -z "$DEBUG" ] || set -x

PROJECT_ROOT="$(cd "$(dirname "$0")"/.. && pwd)"
export PATH="$PROJECT_ROOT/node_modules/.bin:$PATH"

babel recycling-map.js | uglifyjs -c -m > recycling-map.min.js
babel segmented-circle-icon.js | uglifyjs -c -m > segmented-circle-icon.min.js

sass -t compressed style.scss:style.css
