#!/bin/sh

# script/setup: This build the app and then deploys it.

set -e

cd "$(dirname "$0")/.."

script/setup
script/build

## add deployment instructions here..
rsync --progress --exclude node_modules/ --exclude script/ --exclude package.json --exclude package-lock.json --exclude style.scss -avce "ssh -o StrictHostKeyChecking=no" ./ cfruhr@brorsen.uberspace.de:/var/www/virtual/cfruhr/abfallkarte.openruhr.de/

echo "==> App is deployed!"
