#!/bin/sh

# script/setup: This build the app and then deploys it.

set -e

cd "$(dirname "$0")/.."

script/setup
script/build

# deployment instructions here
HOST=cfruhr@musca.uberspace.de
DESTINATION_PATH=/var/www/virtual/cfruhr/abfallkarte.openruhr.de/

ssh -o StrictHostKeyChecking=no $HOST mkdir -p $DESTINATION_PATH
rsync --progress --exclude node_modules/ --exclude script/ --exclude package.json --exclude package-lock.json --exclude style.scss -avce "ssh -o StrictHostKeyChecking=no" ./ $HOST:$DESTINATION_PATH

echo "==> App is deployed!"
